### ISSUE TITLE
Expecting end of input, "ADD", "SUB", "MUL", "DIV", got unexpected "RPAREN".

### ISSUE THREAD

**Issue by luckylooke** [intervolga/optimize-cssnano-plugin#31]
Hello, 

I am getting following error:
```
 ERROR  Error: CSS minification error: Parse error on line 1: 
...--ws-input-height-md, calc(54px + calc(var(--ws-thick-line, 1px) * 2))) * 0.685...
------------------------------------------------------------------------^
Expecting end of input, "ADD", "SUB", "MUL", "DIV", got unexpected "RPAREN". File: css/app.02c38798.css
Error: CSS minification error: Parse error on line 1: 
...--ws-input-height-md, calc(54px + calc(var(--ws-thick-line, 1px) * 2))) * 0.685...
------------------------------------------------------------------------^
Expecting end of input, "ADD", "SUB", "MUL", "DIV", got unexpected "RPAREN". File: css/app.02c38798.css
    at /mnt/AA36F40936F3D473/projects/cart-client/node_modules/@intervolga/optimize-cssnano-plugin/index.js:106:21
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Promise.all (index 0)
```

the CSS is perfectly fine, running locally, it generates valid CSS rules, but your minificator, preinstalled by Vue CLI cannot handle same code 🤷‍♂️

Any idea? Thanks

I have made temporary fix.. to save calculation result into temporary value
```scss
// $ws-input-height-xl: var(--ws-input-height-xl, calc(93px + #{$ws-thick-line-twice})) !default;
// $ws-input-height-md: var(--ws-input-height-md, calc(54px + #{$ws-thick-line-twice})) !default;
// $ws-input-height-sm: var(--ws-input-height-sm, calc(36px + #{$ws-thick-line-twice})) !default;

:root {
  --ws-tmp1: calc(93px + var(--ws-thick-line-twice));
  --ws-tmp2: calc(54px + var(--ws-thick-line-twice));
  --ws-tmp3: calc(36px + var(--ws-thick-line-twice));
}

$ws-input-height-xl: var(--ws-input-height-xl, var(--ws-tmp1)) !default;
$ws-input-height-md: var(--ws-input-height-md, var(--ws-tmp2)) !default;
$ws-input-height-sm: var(--ws-input-height-sm, var(--ws-tmp3)) !default;
```
