### ISSUE TITLE
Query strings in file names break plugin

### ISSUE THREAD

**Issue by wallzero** [intervolga/optimize-cssnano-plugin#8]
I append query strings to my output for cache busting purposes. For example:

```js
new MiniCssExtractPlugin({
  chunkFilename: '[name].css?[chunkhash:' + HASH_LIMIT + ']',
  filename: '[name].css?[chunkhash:' + HASH_LIMIT + ']'
}),
```

However, when I use query strings, my css is no longer minified. [Here is a similiar issue with `optimize-css-assets-webpack-plugin
`](https://github.com/NMFR/optimize-css-assets-webpack-plugin/issues/62)

**Comment by kmohrf** [comment]
It seems like this is not only true for query strings but hashes as well, which breaks SVG fonts and font-face rules that use them.

The following font-face rule will break the build process:

```css
@font-face {
    font-family: 'Source Sans Pro';
    font-weight: 300;
    font-style: normal;
    font-display: swap;
    src: url('./sourcesans pro_300_normal_default.eot');
    src: url('./sourcesans pro_300_normal_default.woff') format('woff'), url('./sourcesans pro_300_normal_default.ttf') format('truetype'), url('./sourcesans pro_300_normal_default.svg#SourceSansPro') format('svg'), url('./sourcesans pro_300_normal_default.eot') format('embedded-opentype');
}
```

After removing the SVG font option, optimize-cssnano-plugin is running fine.
